INSERT INTO  Laptop (id, modelo, marca, precio ) VALUES (1, 'LPA1', 'Lenovo1', 12.3)
INSERT INTO  Laptop (id, modelo, marca, precio ) VALUES (2, 'LPA2', 'Lenovo2', 12.3)
INSERT INTO  Laptop (id, modelo, marca, precio ) VALUES (3, 'LPA3', 'Lenovo3', 12.3)
INSERT INTO  Laptop (id, modelo, marca, precio ) VALUES (4, 'LPA4', 'Lenovo4', 12.3)
INSERT INTO  Laptop (id, modelo, marca, precio ) VALUES (5, 'LPA5', 'Lenovo5', 12.3)
INSERT INTO  Laptop (id, modelo, marca, precio ) VALUES (6, 'LPA6', 'Lenovo6', 12.3)